services:
  minio:
    image: bitnami/minio
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
      MINIO_DEFAULT_BUCKETS: demucs-web
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - storage:/bitnami/minio/data

volumes:
  storage:
